In [1]:
import numpy as np

## numpy array的基本操作: reshape, join, split

### I. reshape
1. 用A.reshape(dim1, dim2, ..., dimN)
   - reshape前后的size要一样，二维条件下size = row * column
   - reshape得到的新array是新建的array，原array形状不变
   - 一维numpy array的shape是(n,)，在broadcast规则中，会被扩展为(1, n)。但它不同于二维shape取(1, n)的场景。

In [2]:
a = np.arange(6)
b = np.arange(6).reshape(1, -1)
print(a, b)
print(a.shape, b.shape)

[0 1 2 3 4 5] [[0 1 2 3 4 5]]
(6,) (1, 6)


In [3]:
b.reshape(2, 3)
b

array([[0, 1, 2, 3, 4, 5]])

2. A.resize(dim1, dim2, ..., dimN)直接改变原array的形状

In [4]:
b.resize(2, 3)
b

array([[0, 1, 2],
       [3, 4, 5]])

3. A.ravel()和A.flatten()会将矩阵flatten。区别是ravel得到的是原始array的View，flatten是copy

In [5]:
c = b.ravel()
d = b.flatten()
d[0] = 100
b, d

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([100,   1,   2,   3,   4,   5]))

In [6]:
c[0] = 100
b, c

(array([[100,   1,   2],
        [  3,   4,   5]]),
 array([100,   1,   2,   3,   4,   5]))

4. 让矩阵增加一个维度，但没有新增元素时，用None或者它的alias：np.newaxis

In [7]:
np.newaxis is None

True

In [8]:
x = np.arange(3)
x.shape, x

((3,), array([0, 1, 2]))

In [9]:
x[np.newaxis, :]

array([[0, 1, 2]])

In [10]:
x[:, np.newaxis, None] # None就是np.newaxis

array([[[0]],

       [[1]],

       [[2]]])

### II. 合并分割: joining and splitting

#### stacking
 - np.vstack(): stacking发生在第一个维度上(first axes)
 - np.hstack(): stacking发生在第二个维度上(second axes)

In [11]:
a = np.array([4., 2.])
b = np.array([3., 8.])
np.vstack((a, b))

array([[4., 2.],
       [3., 8.]])

In [12]:
np.hstack((a, b))

array([4., 2., 3., 8.])

In [13]:
c = np.arange(12).reshape(2, 3, 2)
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [14]:
d = np.ones((2, 3, 2))

In [15]:
np.hstack((c, d)).shape, np.vstack((c, d)).shape

((2, 6, 2), (4, 3, 2))

#### concatenate
 - np.concatenate((a, b, ...), axis=0)可以自定义stacking发生的维度

In [16]:
s = np.concatenate((c, d), axis=2)
s.shape, s

((2, 3, 4),
 array([[[ 0.,  1.,  1.,  1.],
         [ 2.,  3.,  1.,  1.],
         [ 4.,  5.,  1.,  1.]],
 
        [[ 6.,  7.,  1.,  1.],
         [ 8.,  9.,  1.,  1.],
         [10., 11.,  1.,  1.]]]))

#### split
 - np.hsplit(array, indices or section): 在axis=1上分割。
 - np.vsplit(array, indices or section):在axis=1上分割。
 - np.split(array, axis=0, indices or section): 对应前面的concatenate，自定义分割的维度
 - 如果第二个参数是1个整数n，分为n份；如果是tuple，那么tuple中的数字就是分割位置
 - <font color=norange>注：他们返回的结果都是list of arrays.</font>

In [17]:
x = np.arange(24).reshape(2, 4, 3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [18]:
np.hsplit(x, 2)

[array([[[ 0,  1,  2],
         [ 3,  4,  5]],
 
        [[12, 13, 14],
         [15, 16, 17]]]),
 array([[[ 6,  7,  8],
         [ 9, 10, 11]],
 
        [[18, 19, 20],
         [21, 22, 23]]])]

In [19]:
np.hsplit(x, (1, 3))

[array([[[ 0,  1,  2]],
 
        [[12, 13, 14]]]),
 array([[[ 3,  4,  5],
         [ 6,  7,  8]],
 
        [[15, 16, 17],
         [18, 19, 20]]]),
 array([[[ 9, 10, 11]],
 
        [[21, 22, 23]]])]

In [20]:
np.vsplit(x, 2)

[array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]]),
 array([[[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]]])]