In [1]:
import numpy as np
import matplotlib.pyplot as plt
import sys

## I. numpy array的六类基本操作

### 第1类操作：创建
1. 有3种常用的创建方式：\
   (1) 直接用sequence \
   (2) 指定shape和初始值 \
   (3) 用arange或者linspace设置起始值和分割数量
2. 创建时可以直接指定数据类型 \
   <font color=orange>如果不指定，整数默认是int64，浮点数默认是float64</font>

#### 创建例子
1. 直接用sequence创建
 - <font color=orange>array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.</font>

In [2]:
a = np.array([1, 2, 3, 4])
# a = np.array(1, 2, 3, 4)    # WRONG 要用sequence

In [3]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [4]:
c = np.array([[1, 2], [3, 4]], dtype=np.float32)
c.dtype, b.dtype, a.dtype

(dtype('float32'), dtype('float64'), dtype('int64'))

2. 指定shape来初始化矩阵 \
   (1) np.zeros, np.ones, np.empty \
   (2) np.zeros_like, np.ones_like, np.empty_like \
   (3) 默认数据类型是float64，可以直接指定类型

In [5]:
x, y = np.zeros((2, 3), dtype=np.int16), np.empty((2, 3))
x, y

(array([[0, 0, 0],
        [0, 0, 0]], dtype=int16),
 array([[1.5, 2. , 3. ],
        [4. , 5. , 6. ]]))

In [6]:
z = np.ones_like(y, dtype=np.int16)
z

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

3. 设置起始值和分割数量 \
   (1) arange(start, stop, step)，生成的数据范围是[start, stop) \
   (2) linspace(start, stop, number_of_point)，生成的数据范围是[start, stop]
    - <font color=orange>arange能提前知道前后两个point之间的step size，不知道生成的point数量。linspace直接指定生成的point数量</font>

In [7]:
p, q = np.arange(0, 20, 5), np.arange(20, 0, -5) # reverse的时候，step size要设为负数
p, q

(array([ 0,  5, 10, 15]), array([20, 15, 10,  5]))

In [8]:
s, t = np.linspace(0, 2, 9), np.linspace(0, 2, 8, dtype=np.float16)
s, t

(array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ]),
 array([0.    , 0.2856, 0.5713, 0.857 , 1.143 , 1.429 , 1.714 , 2.    ],
       dtype=float16))

In [9]:
# linspace常用于函数自变量取值范围分割
x = np.linspace(0, 2*np.pi, 100)
f = np.sin(s)

4. 打印numpy array

In [10]:
# 当array太大的时候，默认的print会省略一部分内容。如果想打印全部，可以用np.set_printoptions()
np.set_printoptions(threshold=sys.maxsize)
print(np.arange(50).reshape(10, 5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


In [11]:
# 通常还是设置为只打印部分
np.set_printoptions(threshold=10)
print(np.arange(50).reshape(10, 5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 ...
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


### 第2类操作：属性
1. 属性不是函数，是实例的变量
2. 主要的属性有：\
   (1) A.ndim，A.dtype，A.shape \
   (2) A.size是number of elements, A.itemsize是byte size of one elements \
   (3) A.data是数据存储地址

In [12]:
a = np.array([[1., 0., 0.],[0., 1., 2.]])
print(a.ndim, a.shape, a.size)
print(a.dtype, a.itemsize)
print(a.data)

2 (2, 3) 6
float64 8


### 第3类操作：索引 indexing
1. 每个dim一个index，反向索引时index用负数
2. 多维索引用‘,‘隔开
3. fancy indexing

### 第4类操作：切片 slicing
1. 每个维度都用一组start:stop:step, 各个维度之间用','隔开，反向时step取负数
2. slice是引用而非复制，改变slice中的value会同时改变原array中对应位置的值。

### 第5类操作：变形 reshaping
1. 用A.reshape(dim1, dim2, ..., dimN)
注：
1. reshape前后的size要一样，二维条件下size = row * column
2. reshape得到的新array可能是复制，也可能是引用，系统会尽可能处理成复制，但是要看内存分配的连续性。如果要copy就直接用reshape().copy()
3. 一维numpy array的shape是(n,)，在broadcast规则中，会被扩展为(1, n)。但它不同于二维shape取(1, n)的场景。

In [13]:
a = np.arange(5)
b = np.arange(5).reshape(1, -1)
print(a, b)
print(a.shape, b.shape)

[0 1 2 3 4] [[0 1 2 3 4]]
(5,) (1, 5)


### 第6类操作：合并分割 joining and splitting

## II. 数学运算
numpy中针对ndarray的运算基本都是用universal functions来执行的。这些universal function的特点是：
1. operate element-wise on arrays。比如$A*2$是将A中每个元素都*2
2. 支持broadcasting
3. 支持type casting
- <font color=norange>本质上，ufunc是一般function的一个wrapper，把一般function运算改造成了适用于矩阵的运算。</font>

### II.1 数学运算的基本规则

1. 数学运算符在numpy中基本都已经处理成了universal function。所以一般数学运算在numpy array上都是elementwise的。

In [19]:
# elementwise
a = np.array([20, 30, 40, 50])
a < 35

array([ True,  True, False, False])

In [20]:
b = np.arange(4)
b ** 2

array([0, 1, 4, 9])

In [22]:
a - b

array([20, 29, 38, 47])

2. 正常执行数学expression之后，会生成新的numpy array。但如果用的是+=,-=等operator，那么不会生成新的array，等号左边的变量的变化是in place的。\
   <font color=deeppink>**要注意数据类型变化**：
   - 如果两个operant的dtype不一样，会自动做数据类型变换，规则是upcasting，resulting array的类型是更general or precise的那种
   - 如果是+=,-=等operator，发生的是in place赋值，那么要注意左边operant的数据类型无法自动upcast。</font>

In [50]:
# dtype
b = np.random.randn(6)
a, c = np.ones(6, dtype=np.int16), np.ones(6, dtype=np.int16)
print(a.dtype, b.dtype, c.dtype)
b += a
print(b.dtype)

int16 float64 int16
float64


In [53]:
# c += b # 报错，UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int16') 

3. 二元运算的时候，两个operator array的shape要一样。如果不一样，那么要遵守broadcast规则的要求 \
   <font color=norange>**broadcast的两个规则**：
   - 如果两个矩阵的ndims不同，运算的时候自动将它的最左边缺的维度上的size扩展为1，使两个矩阵的ndims相同。比如：一个shape是(n,)的array A与另一个二维array B做运算，会先扩展为(1, n)
   - 两个ndims相同的array做运算，如果它们的shape不同，那么不同的维度上至少其中一个的size必须为1，在size=1的维度上copy，直到两个array的size相同。如果前面例子中array B的shape是(3, n)，那么A会在第一个维度上自我复制，扩展为形状是(3, n)后再跟B做elementwise的运算。</font>

### II.2 常见ufun运算

1. 一般数学运算：+, -, *, /, //, %, **

In [56]:
A = np.array([[2, 0],
              [3, 4]])
print(A // 2)
print(A % 2)

[[1 0]
 [1 2]]
[[0 0]
 [1 0]]


2. 三角运算：sin, cos, tan, arcsin, arccos, arctan, sinh, cosh, tanh ...
3. 比较运算：>, >=, <, <=, ==, !=
4. 位运算和逻辑运算：&(and), |(or), ^(xor)和~(not)
   - 如果operant是int类型，上述operator会执行位运算
   - 如果operant是boolean类型，上述operator会执行逻辑运算。
   - <font color=norange>逻辑运算经常用来做mask</font>

In [58]:
B = np.array([1, 2, 3, 4])
b = np.array([True, False, True, False])
print(~B, ~b)

[-2 -3 -4 -5] [False  True False  True]


In [60]:
c = np.array([9, 12, 3, 4, 5])
mask = (c > 3) & (c < 10)
print(c[mask], c[~mask])

[9 4 5] [12  3]


4. 统计摘要: \
   (1) 返回value：sum, min, max, std, var, mean, median, percentile\
   (2) 返回value index：argmin, argmax\
   (3) any, all：范围boolean scalar\
   (4) prod：返回所有元素相乘的结果scalar

In [96]:
a = np.random.randn(2, 3)
a

array([[-2.24023379,  0.52662732, -1.30715231],
       [-0.31281616,  1.01358176,  0.08734413]])

In [97]:
a.sum(), a.max()

(-2.2326490561549606, 1.0135817611107882)

In [106]:
# 指定axia：规则被指定的dim会被reduce掉
a.sum(axis=0)

array([-2.55304995,  1.54020908, -1.21980818])

In [99]:
np.any(a>0), np.all(a>0)

(True, False)

In [101]:
b = np.arange(10)
c = np.random.choice(b, size=5, replace=True)
c

array([6, 8, 9, 7, 2])

In [105]:
c.argmax(), c.argmin(), np.percentile(c, 4)

(2, 4, 2.64)

5. 2种规则不同的矩阵inner product \
   (1) matmul, 也就是@ \
   (2) dot
- 在两个二维矩阵求内积的时候他们效果一样，两者的差异是：
  - matmul不能用scalar做乘法。 比如不能用：A @ 2
  - matmul中，Stacks of matrices are broadcast together as if the matrices were elements, respecting the signature (n,k),(k,m)->(n,m)

In [86]:
x = np.ones([2, 4])
y = np.ones([4, 3])
z = x @ y
w = np.dot(x, y)
z==w, z.shape

(array([[ True,  True,  True],
        [ True,  True,  True]]),
 (2, 3))

In [89]:
a = np.ones([6, 5, 2, 4])
b = np.ones([6, 5, 4, 3])
c = a @ b # 在最后两个维度上做(2, 4),(4, 3)的inner product，前面的维度视为stack
c.shape

(6, 5, 2, 3)

In [90]:
d = np.dot(a, b)
d.shape

(6, 5, 2, 6, 5, 3)

5. ufunc提供的一些功能性method \
   (1) reduce：在指定维度上执行ufunc运算，同时将该维度reduce掉 \
   (2) accumulate：在指定维度上执行ufunc运算，该维度上保留运算执行到每个elements时候的中间值 \
   (3) outer：外积运算   

In [62]:
a = np.array([2,3,5])
np.add.reduce(a), np.multiply.reduce(a)

(10, 30)

In [63]:
b = np.array([[2,3,5],
              [4, 6, 10]])
np.add.reduce(b, axis=0), np.multiply.reduce(b, axis=1)

(array([ 6,  9, 15]), array([ 30, 240]))

In [64]:
a = np.array([2,3,5])
np.add.accumulate(a), np.multiply.accumulate(a)

(array([ 2,  5, 10]), array([ 2,  6, 30]))