In [1]:
import torch
import math
import torch.nn as nn
import torchviz
# 配置
device = torch.device('cuda')
dtype = torch.float

In [14]:
torch.manual_seed(7)
a = torch.randn((3, 4))
mask = (a > 0).to(torch.int)
a, mask

(tensor([[-0.1468,  0.7861,  0.9468, -1.1143],
         [ 1.6908, -0.8948, -0.3556,  1.2324],
         [ 0.1382, -1.6822,  0.3177,  0.1328]]),
 tensor([[0, 1, 1, 0],
         [1, 0, 0, 1],
         [1, 0, 1, 1]], dtype=torch.int32))

In [41]:
N = 2
C = 10
torch.manual_seed(7)
conv = nn.Conv2d(in_channels=3, out_channels=6, kernel_size=3, padding=0)

x = torch.randn((N, 3, 64, 64), requires_grad=True)

In [43]:
scores = conv(x)
tar_ind = torch.argmax(s, axis=1).view(-1, 1)
tar_score = s.gather(1, tar_ind).squeeze()

saliency = y.abs().max(dim=1)

tar_score

tensor([ 86.9224, 166.3909], grad_fn=<SqueezeBackward0>)

In [44]:
tar_score.sum().backward()
x.grad

tensor([[[[ 1.5142e-01, -7.6450e-02,  7.1000e-01,  ...,  3.1947e-01,
            4.9509e-01, -1.3172e-01],
          [-1.9960e-01, -3.2566e-01,  5.8060e-01,  ..., -4.1881e-01,
            6.2985e-01, -4.4716e-01],
          [-2.9260e-01, -9.9773e-01, -6.7041e-01,  ..., -1.3574e+00,
           -2.6806e-01,  1.9421e-01],
          ...,
          [ 1.2233e-01, -1.3666e+00,  5.4411e-01,  ...,  1.8666e-01,
           -9.0199e-02,  1.3706e-01],
          [-5.5166e-01,  2.9372e-01,  5.4294e-01,  ...,  6.3307e-01,
            1.2115e-01, -2.6955e-01],
          [ 1.6846e-01, -2.0372e-01,  3.0959e-01,  ...,  1.1556e-01,
            1.6999e-01, -6.3866e-02]],

         [[ 3.6823e-01,  3.1229e-01, -1.6630e-01,  ..., -2.5525e-01,
           -6.6940e-02, -1.9454e-01],
          [-1.6650e-01,  3.6783e-01,  6.4801e-01,  ...,  4.8027e-01,
            7.0673e-01, -3.1327e-02],
          [ 3.4554e-01, -7.4015e-02, -7.6807e-01,  ..., -6.9266e-01,
            2.1331e-02,  1.5547e-02],
          ...,
     

In [ ]:
class rktestModule(nn.Module):
    def __init__(self):
        super().__init__()
        self.aff1 = nn.Linear(20, 100)
        self.aff2 = nn.Linear(100, 10)
    
    def forward(self, x):
        x = self.aff1(x)
        x = F.relu(x)
        y = self.aff2(x)
        return y

net = rktestModule()
torch.manual_seed(2)
x = torch.randn(2, 20)
y = torch.randn(2, 10)

score = net(x)
loss = F.cross_entropy(score, y)
loss.backward()